name : Python CLI CI

on :
  push :
    branches : [ "main" ]
jobs :
  build :
    runs-on : ubuntu-latest

    steps :
      - name : Checkout repository
        uses : actions/checkout@v4

      - name : Set up Python
        uses : actions/setup-python@v5
        with : 
          Python-version : '3.13'

      - name : Install dependencies
        run : | 
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
      
      - name : Run linter  
        run : flake8 cli_tools

      - name : Run tests 
        run : pytest  




